### PR TITLE
Cherry-pick: Fixed ApplyPeak exception handling and added TestRunner class name support

### LINKED ISSUE #3811: IOException in ApplyPeak shown as programming defect instead of user-friendly message
## Problem

When a network error occurs while reading the .skyd cache file during "Apply Peak to All", the user sees the unhandled exception dialog suggesting they report a bug, rather than a user-friendly error message.

**Exception report**: https://skyline.ms/home/issues/exceptions/announcements-thread.view?rowId=73735
**Fingerprint**: `078b47ab8d782ab9` (3 reports from 2 users since 2025-07-26)

## Root Cause

`EditMenu.ApplyPeak()` (EditMenu.cs:792-917) lacks exception handling around `longWait.PerformWork()`. When an `IOException` occurs:

1. `ChromatogramCache.CallWithStream()` catches it, closes the stream, re-throws
2. `LongWaitDlg.RunWork()` catches it, stores in `_exception`
3. `LongWaitDlg.PerformWork()` calls `ExceptionUtil.WrapAndThrowException(x)` which re-throws as `IOException`
4. No catch block in `ApplyPeak`, so exception escapes to global handler
5. Global handler shows "programming defect" dialog

The irony is that `IOException` is explicitly recognized as NOT a programming defect by `ExceptionUtil.IsProgrammingDefect()`, but the missing catch block prevents proper handling.

## Suggested Fix

Wrap the `longWait.PerformWork()` call and subsequent code in try-catch, using `ExceptionUtil.DisplayOrReportException()`:

```csharp
try
{
    longWait.PerformWork(SkylineWindow, 1000, progressMonitor =>
    {
        // ... existing code ...
    });
    if (longWait.IsCanceled || document == null)
    {
        return;
    }
    // ... ModifyDocument call ...
}
catch (Exception e)
{
    ExceptionUtil.DisplayOrReportException(SkylineWindow, e);
}
```

This pattern is already used in many places:
- `SkylineFiles.cs:1020` (Panorama download)
- `SkylineFiles.cs:3596`, `3740`
- `PublishDocumentDlgPanorama.cs:115`
- `AllChromatogramsGraph.cs:657`
- And ~20 other locations

## User Impact

Users with .skyd files on network drives who experience temporary network interruptions during "Apply Peak to All" see a scary bug report dialog instead of an actionable message like "An unexpected network error occurred."

### PR DESCRIPTION
**Pull request by brendanx67**
## Summary

Cherry-pick of #3812 to release branch `Skyline/skyline_26_1`.

**Original changes:**
- Fixed ApplyPeak to show user-friendly error for IOExceptions instead of "programming defect" dialog
- Extracted ApplyPeakWithLongWait method for cleaner code structure
- TestRunner now accepts class names (e.g., `test=ApplyPeakToAllTest`) to run all tests in a class

Fixes #3811

### CODE REVIEW

File: pwiz_tools/Skyline/Menus/EditMenu.cs [hunk 1]
```diff
@@ -795,125 +795,136 @@ public void ApplyPeak(bool subsequent, bool group)
...
-                    currentTransitionGroupPath =
-                        SkylineWindow.SequenceTree.SelectedPath.GetPathTo((int) SrmDocument.Level.TransitionGroups);
+                    ApplyPeakWithLongWait(subsequent, group);
                 }
-                var peptidePaths =
-                    SkylineWindow.SequenceTree.SelectedPaths.SelectMany(path =>
-                        document.EnumeratePathsAtLevel(path, SrmDocument.Level.Molecules)).Distinct().ToList();
-                var changedPaths = new List<PropertyName>();
-                if (peptidePaths.Count == 0)
+                catch (Exception e)
```
Comment (nickshulman) [inline pwiz_tools/Skyline/Menus/EditMenu.cs:804]: It does not make much difference but this catch block should probably go outside of the `lock (SkylineWindow.GetDocumentChangeLock())` since we don't need to prevent background document changes while showing an error message.

**Review by nickshulman — APPROVED** [review]
