### PR TITLE
Fix duplicate HeatMapGraph and list forms after document switching

### LINKED ISSUE #4022: TestListClustering: duplicate HeatMapGraph after NewDocument/OpenFile
## Summary

`TestListClustering` has two `HeatMapGraph` forms open simultaneously after a `NewDocument()` + `OpenFile()` sequence. This was exposed by the duplicate-form detection added in PR #4017.

## Root Cause

Two gaps in form lifecycle management:

### 1. `NewDocument()` does not hide/close DataboundGraph forms

When `NewDocument()` is called, the document has no data to display in a HeatMapGraph. However, neither `SwitchDocument()` nor `UpdateGraphUI()` handles DataboundGraph-derived forms (HeatMapGraph, PcaPlot). The HeatMapGraph stays open with stale data.

### 2. `LoadLayoutLocked()` does not destroy DataboundGraph forms before deserializing

`LoadLayoutLocked()` (SkylineGraphs.cs:498) destroys many form types before calling `dockPanel.LoadFromXml()`:
- SequenceTree, Spectrum, FilesTree
- RetentionTime, PeakArea, MassError, Detection graphs
- FoldChangeForm (line 522)
- ResultsGrid, DocumentGrid, AuditLog, Calibration, CandidatePeak
- ImmediateWindow, FindResults, GraphChrom, GraphFullScan

But it does **not** destroy `DataboundGraph` forms (HeatMapGraph, PcaPlot). When the layout is restored from a `.sky.view` file, a new HeatMapGraph is created via `RestoreDataboundGraph()`, resulting in two.

## Reproduction

The `TestListClustering` test flow:
1. Opens a `ListGridForm` and shows a `HeatMapGraph` via `ShowHeatMap()`
2. Saves document (which also saves `.sky.view` via `SaveLayout()`)
3. Calls `NewDocument()` then `OpenFile(savedPath)` in a single `RunUI` block
4. `OpenFile` triggers `LoadLayout()` since `.sky.view` exists, creating HeatMapGraph #2
5. HeatMapGraph #1 was never closed

## Suggested Fix

Add cleanup of DataboundGraph forms, similar to the existing FoldChangeForm cleanup:

In `LoadLayoutLocked()`:
```csharp
FormUtil.OpenForms.OfType<FoldChangeForm>().ForEach(f => f.Close());
FormUtil.OpenForms.OfType<DataboundGraph>().ForEach(f => f.Close());  // Add this
```

Also consider whether `UpdateGraphUI` should hide DataboundGraph forms when the document has no relevant data, so they don't persist through `NewDocument()`.

Once this bug is fixed, the duplicate-form assertion can be moved from `TryWaitForOpenForm()` back into `FindOpenForm()` as a stronger invariant.

## Code Locations

- `SkylineGraphs.cs:498` - `LoadLayoutLocked()` - missing DataboundGraph cleanup
- `SkylineGraphs.cs:236` - `UpdateGraphUI()` - no DataboundGraph handling
- `Controls/Clustering/DataboundGraph.cs` - base class for HeatMapGraph, PcaPlot

## Related

- PR #4017 - Added duplicate-form detection that exposed this issue

### PR DESCRIPTION
**Pull request by brendanx67**
## Summary

* Added `DataboundGraph.CloseInapplicableForms()` and `ListGridForm.CloseInapplicableForms()` to close list-dependent forms when switching to a document that does not contain the list (parallels existing `FoldChangeForm.CloseInapplicableForms()`)
* Close `DataboundGraph` and `ListGridForm` in `LoadLayoutLocked()` before layout deserialization, alongside existing `FoldChangeForm` cleanup
* Added screenshot test infrastructure: full-screen capture and arbitrary rectangle capture via `ScreenshotManager.TakeShot(Rectangle)`
* Added `FindAiTmpPath()` utility to `AbstractUnitTest` for saving test screenshots to `ai/.tmp/`
* Fixed `OpenDocument()` in `AbstractFunctionalTestEx` to handle absolute paths correctly

**Note:** `NewDocument()` preserves list schema and contents from the prior document, so `CloseInapplicableForms()` does not fire on `NewDocument` — the list genuinely still exists. This is noted with a CONSIDER comment in the test for future review.

Fixes #4022

## Test plan

- [x] TestListClustering - verifies no duplicate forms after NewDocument/OpenFile, verifies CloseInapplicableForms closes both ListGridForm and HeatMapGraph when opening document without the list, verifies forms reopen when opening document with the list

Co-Authored-By: Claude <noreply@anthropic.com>

### CODE REVIEW

File: pwiz_tools/Skyline/Controls/Clustering/DataboundGraph.cs [hunk 1]
```diff
@@ -314,6 +315,27 @@ protected void AttachToOwner()
             DataChanged();
         }
 
+        /// <summary>
+        /// Closes DataboundGraph forms whose data source no longer exists in the document,
+        /// analogous to <see cref="pwiz.Skyline.Controls.GroupComparison.FoldChangeForm.CloseInapplicableForms"/>.
+        /// </summary>
+        public static void CloseInapplicableForms(SkylineWindow skylineWindow)
```
Comment (nickshulman) [inline pwiz_tools/Skyline/Controls/Clustering/DataboundGraph.cs]: In theory, these graphs should automatically close themselves when the associated grid closes because of the "DataboundGridControl_OnDisposed" method.
So, the "CloseInapplicableForms" in ListGridForm should be all that's necessary.

Comment (brendanx67) [reply pwiz_tools/Skyline/Controls/Clustering/DataboundGraph.cs]: Good catch. I removed the extraneous graph cleanup.
